name: CI

on: [push]

jobs:
  build_xbox_packs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up env
        run: |
          sudo apt-get install rename -y

      - name: Set up Onyx
        run: |
          sudo apt install libfuse2
          sudo apt install wget
          sudo wget -P dependencies https://github.com/mtolly/onyx/releases/download/20240928/onyx-20240928-linux-x64.AppImage
          sudo chmod a+x dependencies/onyx-20240928-linux-x64.AppImage
          ./dependencies/onyx-20240928-linux-x64.AppImage --appimage-extract

      ########################################################################

      - name: Build RB3 Beta Songs packed CON
        run: |
          python dependencies/pack_single_cons.py RB3-Beta-Songs
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RB3-Beta-Songs_packed
          path: |
            RB3-Beta-Songs_rb3con

      - name: Remove RB3 Beta Songs packed CON
        run: |
          rm RB3-Beta-Songs_rb3con

      ########################################################################

      - name: Build RB3 Lost RBN packed CON
        run: |
          python dependencies/pack_single_cons.py RB3-Lost-RBN
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RB3-Lost-RBN_packed
          path: |
            RB3-Lost-RBN_rb3con

      - name: Remove RB3 Lost RBN packed CON
        run: |
          rm RB3-Lost-RBN_rb3con

      ########################################################################

      - name: Build RB3 Lost RBN 2x packed CON
        run: |
          python dependencies/pack_single_cons.py RB3-Lost-RBN-2x
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RB3-Lost-RBN-2x_packed
          path: |
            RB3-Lost-RBN-2x_rb3con

      - name: Remove RB3-Lost-RBN-2x packed CON
        run: |
          rm RB3-Lost-RBN-2x_rb3con